Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
